name: Testing GH Apps access to other repos
on:
  workflow_dispatch:
env:
  USERNAME: FilipTelia
  REPO_NAME: rel-dep-test

jobs:
  my_job:
    name: Access repos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Generate a JWT using private key and app id
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > .github/private.pem
          sudo chown runner:runner .github/generate-jwt.rb
          ruby .github/generate-jwt.rb ${{ secrets.APP_ID }} > token.txt
          echo "JWT_TOKEN=$(cat token.txt)" >> $GITHUB_ENV
      
      - name: Get Installation Token Using Previously generated JWT and installation id
        run: |         
          json=$(curl --request POST \
          --url "https://api.github.com/app/installations/${{ secrets.INSTALLATION_ID }}/access_tokens" \
          --header "Accept: application/vnd.github+json" \
          --header "Authorization: Bearer ${{ env.JWT_TOKEN }}" \
          --header "X-GitHub-Api-Version: 2022-11-28")
          echo "JSON IS HERE: ${json}"
          token=$( jq -r ".token" <<<"$json" )        
          # echo "$token" | sed 's/./& /g'
          echo "INSTALLATION_TOKEN=$(echo ${token})" >> $GITHUB_ENV
          
      - name: Test Installation Token
        run: |       
          git clone https://x-access-token:${{ env.INSTALLATION_TOKEN }}@github.com/${{ env.USERNAME }}/${{ env.REPO_NAME }}.git
          ls ${{ env.REPO_NAME }}
          
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ env.INSTALLATION_TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/installation/repositories
