name: Testing GH Apps access to other repos
on:
  workflow_dispatch:

jobs:
  my_job:
    name: Access repos
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with GitHub App
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.PRIV_KEY}}" \
            -H "Accept: application/vnd.github.machine-man-preview+json" \
            https://api.github.com/app/installations/${{ secrets.APP_ID }}/access_tokens \
            | jq -r '.token' > token.txt
          
          echo "GITHUB_APP_INSTALLATION_TOKEN=$(cat token.txt)" >> $GITHUB_ENV
          cat token.txt

#      - name: Checkout private repo 1
#        uses: actions/checkout@v2
#        with:
#          repository: myorg/privaterepo1
#          ref: main
#          token: ${{ secrets.GITHUB_APP_INSTALLATION_TOKEN }}
